# Generated by Django 3.0.7 on 2020-10-01 17:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0025_video_q_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ai_auto_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_filter_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_words_per_minute',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
