# Generated by Django 3.0.7 on 2020-09-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0025_video_q_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='q_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
