# Generated by Django 3.0.7 on 2020-10-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0026_video_q_answer'),
        ('videos', '0026_auto_20201001_1756'),
    ]

    operations = [
    ]
