# Generated by Django 3.0.7 on 2020-10-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0027_merge_20201001_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='q_explain',
            field=models.TextField(blank=True, null=True),
        ),
    ]
