# Generated by Django 3.0.7 on 2020-10-19 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20201015_1426'),
        ('videos', '0029_auto_20201019_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Sentence'),
        ),
        migrations.AlterField(
            model_name='label',
            name='subCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.SubCategory'),
        ),
    ]
