# Generated by Django 3.0.7 on 2020-10-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0030_auto_20201019_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='sentence',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='label',
            name='subCategory',
            field=models.BigIntegerField(),
        ),
    ]
