# Generated by Django 3.0.7 on 2020-12-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0031_auto_20201019_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='WPVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField()),
                ('question_id', models.BigIntegerField()),
                ('question_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
