# Generated by Django 3.0.7 on 2021-01-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0034_auto_20210110_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wpvideo',
            name='owner',
        ),
        migrations.AddField(
            model_name='wpvideo',
            name='owner_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
