# Generated by Django 3.1.5 on 2021-01-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0035_auto_20210110_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpvideo',
            name='video_comment',
            field=models.TextField(default='No comments yet'),
        ),
        migrations.AddField(
            model_name='wpvideo',
            name='video_stars',
            field=models.IntegerField(default=5),
        ),
    ]
