# Generated by Django 3.0.7 on 2021-02-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0036_auto_20210127_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_tq_ai_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='is_tq_sample_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
