# Generated by Django 3.0.7 on 2021-02-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0037_auto_20210201_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ai_filter_words_score',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_pace_of_speech_score',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_pause_counter_score',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_performance_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_performance_total_score',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_power_words_score',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_um_counter_score',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_vocabulary_score',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
