# Generated by Django 3.1.5 on 2021-03-04 01:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0038_auto_20210222_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpvideo',
            name='video_comment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), blank=True, null=True, size=None),
        ),
    ]
