# Generated by Django 3.0.7 on 2021-03-04 18:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0039_auto_20210303_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpvideo',
            name='video_comment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500, null=True), blank=True, null=True, size=None),
        ),
    ]
