# Generated by Django 3.0.7 on 2021-03-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0041_auto_20210305_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='ai_category_score',
            field=models.CharField(default='10,10,10,10,10, 10', max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='expert_category_score',
            field=models.CharField(default='10,10,10,10,10,10', max_length=500),
        ),
    ]
