# Generated by Django 3.0.7 on 2021-03-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0042_auto_20210305_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='ai_review_categories',
            field=models.CharField(default='Positive Attitude, Pressure Handling, Problem Solving, Commitment, Leadership, Teamwork', max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='expert_review_categories',
            field=models.CharField(default='Positive Attitude, Pressure Handling, Problem Solving, Commitment, Leadership, Teamwork', max_length=500),
        ),
    ]
