# Generated by Django 3.0.7 on 2021-06-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0043_auto_20210305_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpvideo',
            name='transcripts',
            field=models.TextField(default=''),
        ),
    ]
