# Generated by Django 3.0.7 on 2021-07-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0044_wpvideo_transcripts'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpvideo',
            name='position_id',
            field=models.BigIntegerField(default=-1),
        ),
    ]
