# Generated by Django 3.0.7 on 2021-07-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0045_wpvideo_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpvideo',
            name='video_stars',
            field=models.IntegerField(default=0),
        ),
    ]
