export const GET_VIDEOS = "GET_VIDEOS";
export const GET_VIDEOS_APPLICANT = "GET_VIDEOS_APPLICANT";
export const GET_AUDIOS = "GET_AUDIOS";
export const DELETE_VIDEO = "DELETE_VIDEOS";
export const DELETE_AUDIO = "DELETE_AUDIOS";
export const ADD_VIDEO = "ADD_VIDEO";
export const ADD_AUDIO = "ADD_AUDIO";
export const GET_ERRORS = "GET_ERRORS";

export const CREATE_MESSAGE = "CREATE_MESSAGES";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_FULLNAME_LOADED = "USER_FULLNAME_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_QUESTIONS = "GET_QUESTIONS";
export const NEXT_QUESTION = "NEXT_QUESTION";

export const ADD_REVIEWS = "ADD_REVIEWS";
export const GET_UNREVIEWED_VIDEO = "GET_UNREVIEWED_VIDEO";
export const GET_UNREVIEWED_VIDEO_LIST = "GET_UNREVIEWED_VIDEO_LIST";
export const GET_UNREVIEWED_AUDIO = "GET_UNREVIEWED_AUDIO";

export const PROFILE_LOADED = "PROFILE_LOADED";
export const PROFILE_UPDATED = "PROFILE_UPDATED";

export const VIDEO_UNDER_REVIEW = "VIDEO_UNDER_REVIEW";
export const AUDIO_UNDER_REVIEW = "AUDIO_UNDER_REVIEW";
export const INCREASE_VIDEO_COUNT = "INCREASE_VIDEO_COUNT";
export const INCREASE_AUDIO_COUNT = "INCREASE_AUDIO_COUNT";

export const ADD_RESUME = "ADD_RESUME";
export const GET_RESUMES = "GET_RESUMES";
export const DELETE_RESUME = "DELETE_RESUME";
export const INCREASE_RESUME_COUNT = "INCREASE_RESUME_COUNT";

export const ADD_LABELS = "ADD_LABELS";

export const GET_SUBCATEGORIES = "GET_SUBCATEGORIES";
export const GET_VIDEOSENTENCES = "GET_VIDEOSENTENCES";
export const GET_REVIEW_COUNT = "GET_REVIEW_COUNT";
export const GET_VIDEOUSER = "GET_VIDEOUSER";

export const UPGRADE_ACCOUNTS = "UPGRADE_ACCOUNTS";


export const RESEND_ACTIVATION_EMAIL = "RESEND_ACTIVATION_EMAIL";

export const RETRY_B_QUESTION = "RETRY_B_QUESTION";
export const RETRY_T_QUESTION = "RETRY_T_QUESTION";

export const UPDATE_USER_EMAIL = "UPDATE_USER_EMAIL";

export const ADD_WP_VIDEO = "ADD_WP_VIDEO";
export const GET_RANDOM_QUESTION = "GET_RANDOM_QUESTION";

export const GET_ZP_JOBS = "GET_ZP_JOBS";
export const CHECK_USER_REGISTRATION = "CHECK_USER_REGISTRATION";
export const GET_COMPANY_NAME = "GET_COMPANY_NAME";
export const GET_INTERVIEW_QUESTIONS = "GET_INTERVIEW_QUESTIONS";
export const NEXT_INTERVIEW_QUESTION = "NEXT_INTERVIEW_QUESTION";

export const UPDATE_RECORD = "UPDATE_RECORD";
export const GET_RECORD_STATUS = "GET_RECORD_STATUS";
export const FETCH_PRACTICE_INFO = "FETCH_PRACTICE_INFO";
export const FETCH_INTERVIEW_JOB_INFO = "FETCH_INTERVIEW_JOB_INFO";
export const ADD_POSITION = "ADD_POSITION";

export const GET_POSTED_JOBS = "GET_POSTED_JOBS";
export const ADD_INTERVIEWS = "ADD_INTERVIEWS";

export const GET_RECEIVED_INTERVIEW = "GET_RECEIVED_INTERVIEW";

export const GET_APPLICANT_INFO = "GET_APPLICANT_INFO";

export const SUBMIT_FEEDBACK = "SUBMIT_FEEDBACK";