export const GET_VIDEOS = "GET_VIDEOS";
export const GET_VIDEOS_APPLICANT = "GET_VIDEOS_APPLICANT";
export const GET_AUDIOS = "GET_AUDIOS";
export const DELETE_VIDEO = "DELETE_VIDEOS";
export const DELETE_AUDIO = "DELETE_AUDIOS";
export const ADD_VIDEO = "ADD_VIDEO";
export const ADD_AUDIO = "ADD_AUDIO";
export const GET_ERRORS = "GET_ERRORS";

export const CREATE_MESSAGE = "CREATE_MESSAGES";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_FULLNAME_LOADED = "USER_FULLNAME_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_QUESTIONS = "GET_QUESTIONS";
export const NEXT_QUESTION = "NEXT_QUESTION";

export const ADD_REVIEWS = "ADD_REVIEWS";
export const GET_UNREVIEWED_VIDEO = "GET_UNREVIEWED_VIDEO";
export const GET_UNREVIEWED_VIDEO_LIST = "GET_UNREVIEWED_VIDEO_LIST";
export const GET_UNREVIEWED_AUDIO = "GET_UNREVIEWED_AUDIO";

export const PROFILE_LOADED = "PROFILE_LOADED";
export const PROFILE_UPDATED = "PROFILE_UPDATED";

export const GET_PROFILE_DETAIL = "GET_PROFILE_DETAIL";
export const UPDATE_PERSONAL_INFO = "UPDATE_PERSONAL_INFO";
export const UPDATE_SOCIAL_MEDIA = "UPDATE_SOCIAL_MEDIA";
export const UPDATE_BASIC_INFO = "UPDATE_BASIC_INFO";
export const UPDATE_VIDEO = "UPDATE_VIDEO";
export const UPDATE_SUMMARY = "UPDATE_SUMMARY";
export const UPDATE_RESUME = "UPDATE_RESUME";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";
export const UPDATE_WORK_EXP = "UPDATE_WORK_EXP";
export const UPDATE_PROFILE_RATE = "UPDATE_PROFILE_RATE";
export const UPDATE_USER_LOGO = "UPDATE_USER_LOGO";
export const UPDATE_JOB_TYPE = "UPDATE_JOB_TYPE";
export const UPDATE_SKILLS = "UPDATE_SKILLS";
export const UPDATE_LANGUAGES = "UPDATE_LANGUAGES";
export const UPDATE_PROFILE_SHARING = "UPDATE_PROFILE_SHARING";
export const CREATE_PROFILE = "CREATE_PROFILE";
export const DELETE_PROFILE_EDUCATION = "DELETE_PROFILE_EDUCATION";
export const DELETE_PROFILE_WORK_EXP = "DELETE_PROFILE_WORK_EXP";

export const GET_EMPLOYER_PROFILE_DETAIL = "GET_EMPLOYER_PROFILE_DETAIL";
export const UPDATE_EMPLOYER_INFO = "UPDATE_EMPLOYER_INFO";
export const UPDATE_EMPLOYER_SOCIAL_MEDIA = "UPDATE_EMPLOYER_SOCIAL_MEDIA";
export const UPDATE_EMPLOYER_BASIC_INFO = "UPDATE_EMPLOYER_BASIC_INFO";
export const UPDATE_EMPLOYER_VIDEO = "UPDATE_EMPLOYER_VIDEO";
export const UPDATE_EMPLOYER_SUMMARY = "UPDATE_EMPLOYER_SUMMARY";
export const UPDATE_EMPLOYER_LOGO = "UPDATE_EMPLOYER_LOGO";
export const CREATE_EMPLOYER_PROFILE = "CREATE_EMPLOYER_PROFILE";

export const ADD_EMPLOYER_POST = "ADD_EMPLOYER_POST";
export const UPDATE_EMPLOYER_POST = "UPDATE_EMPLOYER_POST";
export const GET_EMPLOYER_POST = "GET_EMPLOYER_POST";
export const DELETE_EMPLOYER_POST = "DELETE_EMPLOYER_POST";

export const VIDEO_UNDER_REVIEW = "VIDEO_UNDER_REVIEW";
export const AUDIO_UNDER_REVIEW = "AUDIO_UNDER_REVIEW";
export const INCREASE_VIDEO_COUNT = "INCREASE_VIDEO_COUNT";
export const INCREASE_AUDIO_COUNT = "INCREASE_AUDIO_COUNT";

export const ADD_RESUME = "ADD_RESUME";
export const GET_RESUMES = "GET_RESUMES";
export const DELETE_RESUME = "DELETE_RESUME";
export const INCREASE_RESUME_COUNT = "INCREASE_RESUME_COUNT";

export const ADD_LABELS = "ADD_LABELS";

export const GET_SUBCATEGORIES = "GET_SUBCATEGORIES";
export const GET_VIDEOSENTENCES = "GET_VIDEOSENTENCES";
export const GET_REVIEW_COUNT = "GET_REVIEW_COUNT";
export const GET_VIDEOUSER = "GET_VIDEOUSER";

export const UPGRADE_ACCOUNTS = "UPGRADE_ACCOUNTS";


export const RESEND_ACTIVATION_EMAIL = "RESEND_ACTIVATION_EMAIL";

export const RETRY_B_QUESTION = "RETRY_B_QUESTION";
export const RETRY_T_QUESTION = "RETRY_T_QUESTION";

export const UPDATE_USER_EMAIL = "UPDATE_USER_EMAIL";

export const ADD_WP_VIDEO = "ADD_WP_VIDEO";
export const GET_RANDOM_QUESTION = "GET_RANDOM_QUESTION";

export const GET_ZP_JOBS = "GET_ZP_JOBS";
export const CHECK_USER_REGISTRATION = "CHECK_USER_REGISTRATION";
export const GET_COMPANY_NAME = "GET_COMPANY_NAME";
export const GET_INTERVIEW_QUESTIONS = "GET_INTERVIEW_QUESTIONS";
export const NEXT_INTERVIEW_QUESTION = "NEXT_INTERVIEW_QUESTION";
export const GET_QUESTION_LIST = "GET_QUESTION_LIST";

export const UPDATE_RECORD = "UPDATE_RECORD";
export const UPDATE_RECORD_REFRESH = "UPDATE_RECORD_REFRESH";
export const GET_RECORD_STATUS = "GET_RECORD_STATUS";
export const FETCH_PRACTICE_INFO = "FETCH_PRACTICE_INFO";
export const FETCH_INTERVIEW_JOB_INFO = "FETCH_INTERVIEW_JOB_INFO";
export const ADD_POSITION = "ADD_POSITION";
export const CLOSE_POSITION = "CLOSE_POSITION";
export const DELETE_POSITION = "DELETE_POSITION";

export const GET_POSTED_JOBS = "GET_POSTED_JOBS";
export const ADD_INTERVIEWS = "ADD_INTERVIEWS";
export const MOVE_CANDIDATE_TO_INTERVIEW = "MOVE_CANDIDATE_TO_INTERVIEW";
export const SEND_VIDEO_INTERVIEWS = "SEND_VIDEO_INTERVIEWS";
export const RESEND_INVITATION = "RESEND_INVITATION";
export const UPDATE_COMMENT_STATUS = "UPDATE_COMMENT_STATUS";
export const UPDATE_VIEW_STATUS = "UPDATE_VIEW_STATUS";

export const GET_RECEIVED_INTERVIEW = "GET_RECEIVED_INTERVIEW";

export const GET_APPLICANT_INFO = "GET_APPLICANT_INFO";
export const GET_APPLICANTS_DATA = "GET_APPLICANTS_DATA";

export const SUBMIT_FEEDBACK = "SUBMIT_FEEDBACK";

export const UPDATE_VIDEO_COMMENTS = "UPDATE_VIDEO_COMMENTS";

export const EMPLOYER_NOTIFICATION = "EMPLOYER_NOTIFICATION";

export const ADD_TQ_VIDEO_LIMIT = "ADD_TQ_VIDEO_LIMIT";

export const GET_RESUME_URL = "GET_RESUME_URL";

export const UPDATE_SECONDROUND_STATUS = "UPDATE_SECONDROUND_STATUS";

export const GET_RESUME_URL_ERROR = "GET_RESUME_URL_ERROR";

export const UPDATE_STARS_LIST = "UPDATE_STARS_LIST";

export const ADD_SUB_REVIEWER = "ADD_SUB_REVIEWER";

export const REMOVE_SUB_REVIEWER = "REMOVE_SUB_REVIEWER";

export const GET_ANALYTICS_INFO = "GET_ANALYTICS_INFO";

export const SUBREVIEWER_UPDATE_COMMENT = "SUBREVIEWER_UPDATE_COMMENT";

export const ADD_NEW_JOB = "ADD_NEW_JOB";
export const GET_ALL_JOBS = "GET_ALL_JOBS";
export const UPDATE_JOB = "UPDATE_JOB";
export const ARCHIVE_JOB = "ARCHIVE_JOB";
export const ADD_NEW_APPLY_CANDIDATE = "ADD_NEW_APPLY_CANDIDATE";
export const GET_CURRENT_JOBS = "GET_CURRENT_JOBS";
export const ADD_INTERVIEW_QUESTION = "ADD_INTERVIEW_QUESTION";
export const UPDATE_INVITE_STATUS = "UPDATE_INVITE_STATUS";
export const DELETE_JOB = "DELETE_JOB";
export const GET_JOBID_LIST="GET_JOBID_LIST";

export const UPDATE_CANDIDATA_VIEWED_STATUS = "UPDATE_CANDIDATA_VIEWED_STATUS";
export const DELETE_INTERVIEW_QUESTIONS = "DELETE_INTERVIEW_QUESTIONS";

export const ADD_EXTERNAL_REVIEWER = "ADD_EXTERNAL_REVIEWER";
export const DELETE_EXTERNAL_REVIEWER = "DELETE_EXTERNAL_REVIEWER";
export const CHECK_USER_EXISTENCE = "CHECK_USER_EXISTENCE";

export const GET_ZR_FEED_XML = "GET_ZR_FEED_XML";
export const GET_ZR_PREMIUM_FEED_XML = "GET_ZR_PREMIUM_FEED_XML";

export const GET_COMAPNY_BRANDING_INFO = "GET_COMAPNY_BRANDING_INFO";

export const CHECK_COMPANY_NAME_EXISTENCE = "CHECK_COMPANY_NAME_EXISTENCE";

export const GET_RESUME_FROM_JOB_APPLICATION = "GET_RESUME_FROM_JOB_APPLICATION";

export const ADD_REVIEW_NOTE = "ADD_REVIEW_NOTE";
export const GET_REVIEW_NOTE = "GET_REVIEW_NOTE";

export const ADD_OR_UPDATE_REVIEWER_EVALUATION = "ADD_OR_UPDATE_REVIEWER_EVALUATION";
export const GET_REVIEWER_EVALUATION = "GET_REVIEWER_EVALUATION";
export const GET_CURRENT_EVALUATION = "GET_CURRENT_EVALUATION";

export const GET_REVIEWERS_LIST = "GET_REVIEWERS_LIST";
export const REMOVE_REVIEWER_FROM_LIST = "REMOVE_REVIEWER_FROM_LIST";
export const CREATE_MERGE_LINK_TOKEN = "CREATE_MERGE_LINK_TOKEN";
export const RETRIEVE_MERGE_ACCOUNT_TOKEN = "RETRIEVE_MERGE_ACCOUNT_TOKEN";
export const CHECK_FREE_ACCOUNT_ACTIVE_JOBS = "CHECK_FREE_ACCOUNT_ACTIVE_JOBS";
export const SEND_MERGE_API_REQUEST = "SEND_MERGE_API_REQUEST";
export const ADD_CAND_FROM_MERGE = "ADD_CAND_FROM_MERGE";

export const GET_SOURCING_DATA = "GET_SOURCING_DATA";