# Generated by Django 3.0.7 on 2023-01-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('catefory', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
