# Generated by Django 3.0.7 on 2023-01-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_djangouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.BooleanField(default=False)),
                ('datejoined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
