# Generated by Django 3.0.7 on 2023-01-30 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoUser',
        ),
    ]
