# Generated by Django 3.0.7 on 2023-01-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230130_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='catefory',
            new_name='category',
        ),
    ]
