# Generated by Django 3.0.7 on 2023-01-30 09:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230130_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='items',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='quantity',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='is_done',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='item_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='item_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=50), blank=True, null=True, size=None),
        ),
    ]
