# Generated by Django 3.0.7 on 2023-01-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230130_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
