# Generated by Django 3.0.7 on 2020-07-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sub_canceled',
            field=models.BooleanField(default=True),
        ),
    ]
