# Generated by Django 3.0.7 on 2020-07-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_sub_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sub_canceled',
        ),
    ]
