# Generated by Django 3.0.7 on 2020-08-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.CharField(blank=True, default='https://hirebeat-assets.s3.amazonaws.com/user.png', max_length=1000, null=True),
        ),
    ]
