# Generated by Django 3.0.7 on 2020-10-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20201012_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='plan_interval',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
