# Generated by Django 3.0.7 on 2020-10-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20201021_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='Not provided', max_length=12),
        ),
    ]
