# Generated by Django 3.0.7 on 2020-11-13 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20201028_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='save_limit',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(5)]),
        ),
    ]
