# Generated by Django 3.0.7 on 2021-01-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20201113_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
    ]
