# Generated by Django 3.0.7 on 2021-01-07 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_interviewquestions_invitedcandidates_positions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0024_profile_is_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='CandidatesInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('positions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.Positions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
