# Generated by Django 3.0.7 on 2021-01-07 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_interviewquestions_invitedcandidates_positions'),
        ('accounts', '0025_auto_20210107_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesinterview',
            name='positions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Positions'),
        ),
    ]
