# Generated by Django 3.0.7 on 2021-01-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210107_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatesinterview',
            name='user',
        ),
        migrations.AddField(
            model_name='candidatesinterview',
            name='is_recorded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidatesinterview',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
