# Generated by Django 3.0.7 on 2021-01-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210108_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesinterview',
            name='url_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
