# Generated by Django 3.0.7 on 2021-01-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_candidatesinterview_url_clicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesinterview',
            name='video_count',
            field=models.IntegerField(default=0),
        ),
    ]
