# Generated by Django 3.0.7 on 2021-01-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_candidatesinterview_video_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatesinterview',
            name='video_count',
        ),
    ]
