# Generated by Django 3.0.7 on 2021-02-26 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_candidatesinterview_video_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='feedback_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='feedback_limit',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(2)]),
        ),
    ]
