# Generated by Django 3.0.7 on 2021-02-26 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20210226_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='save_resume_limit',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
