# Generated by Django 3.0.7 on 2021-03-05 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20210302_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reviewer_count',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
