# Generated by Django 3.0.7 on 2021-03-08 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20210305_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='candidate_limit',
            field=models.IntegerField(default=25, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='position_limit',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
