# Generated by Django 3.0.7 on 2021-03-10 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20210308_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
