# Generated by Django 3.0.7 on 2021-03-24 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0036_profile_position_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('self_description', models.TextField(blank=True, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('github', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_exp', models.IntegerField(default=0)),
                ('current_company', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('video_url', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('school1', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation_date1', models.CharField(blank=True, max_length=100, null=True)),
                ('degree1', models.CharField(blank=True, max_length=100, null=True)),
                ('major1', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_major1', models.CharField(blank=True, max_length=100, null=True)),
                ('gpa1', models.CharField(blank=True, max_length=100, null=True)),
                ('school2', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation_date2', models.CharField(blank=True, max_length=100, null=True)),
                ('degree2', models.CharField(blank=True, max_length=100, null=True)),
                ('major2', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_major2', models.CharField(blank=True, max_length=100, null=True)),
                ('gpa2', models.CharField(blank=True, max_length=100, null=True)),
                ('school3', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation_date3', models.CharField(blank=True, max_length=100, null=True)),
                ('degree3', models.CharField(blank=True, max_length=100, null=True)),
                ('major3', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_major3', models.CharField(blank=True, max_length=100, null=True)),
                ('gpa3', models.CharField(blank=True, max_length=100, null=True)),
                ('company1', models.CharField(blank=True, max_length=100, null=True)),
                ('title1', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date1', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date1', models.CharField(blank=True, max_length=100, null=True)),
                ('work_description1', models.TextField(blank=True, null=True)),
                ('company2', models.CharField(blank=True, max_length=100, null=True)),
                ('title2', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date2', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date2', models.CharField(blank=True, max_length=100, null=True)),
                ('work_description2', models.TextField(blank=True, null=True)),
                ('company3', models.CharField(blank=True, max_length=100, null=True)),
                ('title3', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date3', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date3', models.CharField(blank=True, max_length=100, null=True)),
                ('work_description3', models.TextField(blank=True, null=True)),
                ('company4', models.CharField(blank=True, max_length=100, null=True)),
                ('title4', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date4', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date4', models.CharField(blank=True, max_length=100, null=True)),
                ('work_description4', models.TextField(blank=True, null=True)),
                ('company5', models.CharField(blank=True, max_length=100, null=True)),
                ('title5', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date5', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date5', models.CharField(blank=True, max_length=100, null=True)),
                ('work_description5', models.TextField(blank=True, null=True)),
                ('resume_name', models.CharField(blank=True, max_length=100, null=True)),
                ('resume_url', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
