# Generated by Django 3.0.7 on 2021-03-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_profiledetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetail',
            name='year_of_exp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
