# Generated by Django 3.0.7 on 2021-03-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20210326_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetail',
            name='profile_rate',
            field=models.IntegerField(default=25),
        ),
    ]
