# Generated by Django 3.0.7 on 2021-03-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_profiledetail_profile_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetail',
            name='info_rate',
            field=models.IntegerField(default=0),
        ),
    ]
