# Generated by Django 3.0.7 on 2021-04-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_employerpost_employerprofiledetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofiledetail',
            name='logo_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
