# Generated by Django 3.0.7 on 2021-05-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_employerprofiledetail_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetail',
            name='logo_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
