# Generated by Django 3.0.7 on 2021-06-02 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_profile_viewed_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='external_reviewer_count',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
