# Generated by Django 3.0.7 on 2021-06-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_profile_external_reviewer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_external_reviewer',
            field=models.BooleanField(default=False),
        ),
    ]
