# Generated by Django 3.0.7 on 2021-06-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_profile_is_external_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofiledetail',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
