# Generated by Django 3.0.7 on 2021-06-14 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_employerprofiledetail_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='external_reviewer_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reviewer_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
