# Generated by Django 3.0.7 on 2021-06-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20210614_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofiledetail',
            name='company_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
