# Generated by Django 3.0.7 on 2021-07-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_employerprofiledetail_company_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='merge_public_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
