# Generated by Django 3.0.7 on 2021-08-12 19:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_profile_merge_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetail',
            name='current_job_title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='profiledetail',
            name='f_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profiledetail',
            name='job_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profiledetail',
            name='l_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profiledetail',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='profiledetail',
            name='share_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profiledetail',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=50), blank=True, null=True, size=None),
        ),
    ]
