# Generated by Django 3.0.7 on 2021-08-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20210812_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetail',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profiledetail',
            name='open_to_hr',
            field=models.BooleanField(default=False),
        ),
    ]
