# Generated by Django 3.0.7 on 2021-08-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20210813_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_freetrial',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='membership',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Premium', 'Premium'), ('Prestige', 'Prestige')], default='Premium', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan_interval',
            field=models.CharField(default='Premium', max_length=30),
        ),
    ]
