# Generated by Django 3.0.7 on 2021-08-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20210813_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofiledetail',
            name='f_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employerprofiledetail',
            name='l_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
