# Generated by Django 3.0.7 on 2021-08-18 18:44

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20210818_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='datejoined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='candidate_limit',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position_limit',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
