# Generated by Django 3.0.7 on 2021-08-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_auto_20210818_1444'),
        ('accounts', '0053_auto_20210819_1354'),
    ]

    operations = [
    ]
