# Generated by Django 3.0.7 on 2021-08-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_merge_20210819_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='membership',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Premium', 'Premium'), ('Prestige', 'Prestige')], default='Regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan_interval',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
