# Generated by Django 3.0.7 on 2021-09-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20210824_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetail',
            name='profile_rate',
            field=models.IntegerField(default=5),
        ),
    ]
