# Generated by Django 3.0.7 on 2021-09-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_auto_20210909_1402'),
        ('accounts', '0057_profiledetaileducation_profiledetailexperience'),
    ]

    operations = [
    ]
