# Generated by Django 3.0.7 on 2021-10-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_merge_20210910_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ats_api_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
