# Generated by Django 3.0.7 on 2022-03-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_paygcredittojob'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('plan', models.CharField(blank=True, max_length=100, null=True)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('dateredeemed', models.DateTimeField(null=True)),
            ],
        ),
    ]
