# Generated by Django 3.0.7 on 2022-04-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_redeemcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('delete_date', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
