# Generated by Django 3.0.7 on 2022-04-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_deletedaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='requestDelete',
            field=models.BooleanField(default=False),
        ),
    ]
