# Generated by Django 3.0.7 on 2022-04-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_profile_requestdelete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='requestDelete',
            new_name='request_delete',
        ),
    ]
