# Generated by Django 3.0.7 on 2022-04-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_auto_20220406_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemcode',
            name='userid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
