# Generated by Django 3.0.7 on 2022-05-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_redeemcode_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jobt_company_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='jobt_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='jobt_user_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
