# Generated by Django 3.0.7 on 2022-05-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_redeemcode_userid'),
        ('accounts', '0066_auto_20220502_0242'),
    ]

    operations = [
    ]
