# Generated by Django 3.0.7 on 2022-05-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_auto_20220510_1227'),
        ('accounts', '0067_merge_20220507_0236'),
    ]

    operations = [
    ]
