# Generated by Django 3.0.7 on 2022-05-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_merge_20220516_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jobt_job_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
