# Generated by Django 3.0.7 on 2022-07-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_auto_20220525_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan_selected',
            field=models.BooleanField(default=False),
        ),
    ]
