# Generated by Django 3.0.7 on 2022-05-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_auto_20220525_1142'),
        ('accounts', '0070_remove_profile_jobt_job_id'),
    ]

    operations = [
    ]
