# Generated by Django 3.0.7 on 2022-07-25 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_profile_plan_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_freetrial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position_limit',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
