# Generated by Django 3.0.7 on 2022-08-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_email_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_logs',
            name='user',
        ),
        migrations.AddField(
            model_name='email_logs',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
