# Generated by Django 3.0.7 on 2022-08-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_merge_20220525_1549'),
        ('accounts', '0073_email_logs'),
    ]

    operations = [
    ]
