# Generated by Django 3.0.7 on 2020-10-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200929_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_title',
            field=models.CharField(default='Not Provided', max_length=200, null=True),
        ),
    ]
