# Generated by Django 3.0.7 on 2020-10-12 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20201012_1018'),
        ('resume', '0004_resume_job_title'),
    ]

    operations = [
    ]
