# Generated by Django 3.0.7 on 2020-10-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20201013_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ats_findings_count_total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='rec_findings_count_total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills_match_count_total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
