# Generated by Django 3.0.7 on 2020-09-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20200923_1606'),
        ('questions', '0009_auto_20200923_1531'),
    ]

    operations = [
    ]
