# Generated by Django 3.0.7 on 2020-09-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_merge_20200923_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Positive Attitude', 'Positive Attitude'), ('Work Commitment', 'Work Commitment'), ('Teamwork Skill', 'Teamwork Skill'), ('Leadership', 'Leadership'), ('Pressure Handling', 'Pressure Handling'), ('Proactive Skill', 'Proactive Skill'), ('Work Ethic', 'Work Ethic'), ('Creativity', 'Creativity'), ('Reliability', 'Reliability'), ('Detail Oriented', 'Detail Oriented'), ('Communication Skill', 'Communication Skill'), ('Problem Solving', 'Problem Solving'), ('Accounting', 'Accounting'), ('Administrate Support', 'Administrate Support'), ('Consulting', 'Consulting'), ('Finance', 'Finance'), ('Human Resources', 'Human Resources'), ('Marketing', 'Marketing'), ('Product Management', 'Product Management'), ('Retail', 'Retail')], default='Positive Attitude', max_length=50),
        ),
    ]
