# Generated by Django 3.0.7 on 2020-10-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explain',
            field=models.TextField(blank=True, null=True),
        ),
    ]
