# Generated by Django 3.0.7 on 2020-10-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20201015_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorys',
            name='question',
        ),
        migrations.RemoveField(
            model_name='categorys',
            name='subCategory',
        ),
    ]
