# Generated by Django 3.0.7 on 2020-10-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20201015_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorys',
            name='question',
        ),
        migrations.AddField(
            model_name='categorys',
            name='questions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
