# Generated by Django 3.0.7 on 2021-01-07 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0015_auto_20201029_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=300, null=True)),
                ('job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvitedCandidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('invite_date', models.DateTimeField(auto_now_add=True)),
                ('positions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Positions')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='No description', null=True)),
                ('positions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Positions')),
            ],
        ),
    ]
