# Generated by Django 3.0.7 on 2021-01-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_interviewfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedcandidates',
            name='is_recorded',
            field=models.BooleanField(default=False),
        ),
    ]
