# Generated by Django 3.1.5 on 2021-01-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_interviewfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedcandidates',
            name='comment_status',
            field=models.IntegerField(default=0),
        ),
    ]
