# Generated by Django 3.0.7 on 2021-01-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_invitedcandidates_is_recorded'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
