# Generated by Django 3.1.5 on 2021-01-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_invitedcandidates_comment_status'),
        ('questions', '0018_invitedcandidates_is_recorded'),
    ]

    operations = [
    ]
