# Generated by Django 3.1.5 on 2021-01-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_interviewfeedback_email'),
        ('questions', '0019_merge_20210119_1515'),
    ]

    operations = [
    ]
