# Generated by Django 3.0.7 on 2021-01-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_invitedcandidates_video_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
