# Generated by Django 3.0.7 on 2021-01-28 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_positions_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='invite_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 27, 16, 55, 7, 807583)),
        ),
    ]
