# Generated by Django 3.0.7 on 2021-01-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_positions_invite_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='invite_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
