# Generated by Django 3.1.5 on 2021-02-08 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0025_positions_questiontime'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewResumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumeURL', models.URLField()),
                ('invite_date', models.DateTimeField(auto_now_add=True)),
                ('candidateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('positionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.positions')),
            ],
        ),
    ]
