# Generated by Django 3.0.7 on 2021-02-16 22:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_positions_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresumes',
            name='basic_cri_info_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='basic_cri_jd_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='basic_cri_resume_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='hard_skill_info_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='hard_skill_jd_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='hard_skill_resume_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='other_keyword_info_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='other_keyword_jd_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='other_keyword_resume_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='result_rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='soft_skill_info_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='soft_skill_jd_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='soft_skill_resume_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=50), blank=True, null=True, size=None),
        ),
    ]
