# Generated by Django 3.1.5 on 2021-02-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_auto_20210216_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedcandidates',
            name='secondround_status',
            field=models.IntegerField(default=0),
        ),
    ]
