# Generated by Django 3.0.7 on 2021-02-18 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_auto_20210216_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedcandidates',
            name='accept_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
