# Generated by Django 3.0.7 on 2021-02-18 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_invitedcandidates_secondround_status'),
        ('questions', '0029_invitedcandidates_accept_date'),
    ]

    operations = [
    ]
