# Generated by Django 3.0.7 on 2021-02-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_merge_20210218_2359'),
        ('questions', '0030_merge_20210218_2330'),
    ]

    operations = [
    ]
