# Generated by Django 3.0.7 on 2021-03-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_merge_20210218_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
