# Generated by Django 3.0.7 on 2021-03-02 18:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0031_question_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubReviewers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(blank=True, max_length=30, null=True)),
                ('r_email', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('positions_id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=10), blank=True, null=True, size=None)),
            ],
        ),
    ]
