# Generated by Django 3.0.7 on 2021-03-02 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0032_subreviewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subreviewers',
            name='positions_id',
        ),
        migrations.AddField(
            model_name='subreviewers',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Positions'),
        ),
    ]
