# Generated by Django 3.0.7 on 2021-03-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0033_auto_20210302_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedcandidates',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
