# Generated by Django 3.0.7 on 2021-06-02 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0034_invitedcandidates_is_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalReviewers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(blank=True, max_length=30, null=True)),
                ('r_email', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Positions')),
            ],
        ),
    ]
