# Generated by Django 3.0.7 on 2021-06-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0037_auto_20210611_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positions',
            old_name='response_time',
            new_name='questionTime',
        ),
    ]
