# Generated by Django 3.0.7 on 2021-06-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0038_auto_20210611_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedcandidates',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
    ]
