# Generated by Django 3.0.7 on 2021-06-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0039_invitedcandidates_is_invited'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
