# Generated by Django 3.0.7 on 2021-06-20 05:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0040_interviewnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewnote',
            name='applicant_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviewnote',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Positions'),
        ),
        migrations.AddField(
            model_name='interviewnote',
            name='review_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewnote',
            name='reviewer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
