# Generated by Django 3.0.7 on 2021-06-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0041_auto_20210620_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedcandidates',
            name='resume_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
