# Generated by Django 3.0.7 on 2021-06-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0043_auto_20210622_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reviewer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('evaluation', models.IntegerField(default=0)),
                ('applicant_email', models.CharField(blank=True, max_length=100, null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Positions')),
            ],
        ),
    ]
