# Generated by Django 3.0.7 on 2021-07-15 15:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0045_auto_20210628_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresumes',
            name='extra_skills_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='extra_skills_occurrence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='extra_skills_on_resume',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='required_skills_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='required_skills_occurrence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='required_skills_on_resume',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='transferable_skills_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='transferable_skills_occurrence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='interviewresumes',
            name='transferable_skills_on_resume',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='invitedcandidates',
            name='extra_skills_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='invitedcandidates',
            name='extra_skills_occurrence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='invitedcandidates',
            name='extra_skills_on_resume',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='invitedcandidates',
            name='required_skills_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='invitedcandidates',
            name='required_skills_occurrence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='invitedcandidates',
            name='required_skills_on_resume',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='invitedcandidates',
            name='transferable_skills_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='invitedcandidates',
            name='transferable_skills_occurrence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='invitedcandidates',
            name='transferable_skills_on_resume',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), blank=True, null=True, size=None),
        ),
    ]
