# Generated by Django 3.0.7 on 2021-07-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0045_auto_20210628_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitedcandidates',
            name='resume_url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
