# Generated by Django 3.0.7 on 2021-07-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0046_auto_20210714_1756'),
        ('questions', '0046_auto_20210715_1117'),
    ]

    operations = [
    ]
