# Generated by Django 3.0.7 on 2021-09-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0048_auto_20210726_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedcandidates',
            name='current_stage',
            field=models.CharField(default='Video Interview', max_length=100),
        ),
    ]
