# Generated by Django 3.0.7 on 2021-09-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0049_invitedcandidates_current_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalreviewers',
            name='current_stage',
            field=models.CharField(default='All', max_length=100),
        ),
        migrations.AddField(
            model_name='externalreviewers',
            name='jobs_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='externalreviewers',
            name='master_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invitedcandidates',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subreviewers',
            name='current_stage',
            field=models.CharField(default='Resume Review', max_length=100),
        ),
        migrations.AddField(
            model_name='subreviewers',
            name='jobs_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subreviewers',
            name='master_user',
            field=models.IntegerField(default=0),
        ),
    ]
