# Generated by Django 3.0.7 on 2021-10-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0050_auto_20210927_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedcandidates',
            name='gh_applications_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
