# Generated by Django 3.0.7 on 2021-10-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0051_invitedcandidates_gh_applications_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='job_id_in_jobs',
            field=models.BigIntegerField(default=0),
        ),
    ]
