# Generated by Django 3.0.7 on 2021-10-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0052_positions_job_id_in_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewnote',
            name='current_stage',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reviewerevaluation',
            name='current_stage',
            field=models.CharField(default='', max_length=100),
        ),
    ]
