# Generated by Django 3.0.7 on 2022-01-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0054_interviewnote_reviewer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedcandidates',
            name='livcat',
            field=models.CharField(default='TBD', max_length=50),
        ),
        migrations.AddField(
            model_name='positions',
            name='livcat1',
            field=models.CharField(default='First Round', max_length=50),
        ),
        migrations.AddField(
            model_name='positions',
            name='livcat2',
            field=models.CharField(default='Second Round', max_length=50),
        ),
        migrations.AddField(
            model_name='positions',
            name='livcat3',
            field=models.CharField(default='Third Round', max_length=50),
        ),
        migrations.AddField(
            model_name='positions',
            name='livcat4',
            field=models.CharField(default='Fourth Round', max_length=50),
        ),
        migrations.AddField(
            model_name='positions',
            name='livcat5',
            field=models.CharField(default='Final Round', max_length=50),
        ),
    ]
