# Generated by Django 3.0.7 on 2021-04-13 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0034_invitedcandidates_is_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=300, null=True)),
                ('job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_location', models.CharField(blank=True, max_length=300, null=True)),
                ('job_level', models.CharField(blank=True, max_length=100, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('job_status', models.CharField(default='Published', max_length=100)),
                ('job_url', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('positions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Positions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
