# Generated by Django 3.0.7 on 2021-04-14 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_applycandidates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applycandidates',
            old_name='phone_num',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='applycandidates',
            name='apply_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applycandidates',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
