# Generated by Django 3.0.7 on 2021-04-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210414_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycandidates',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
    ]
