# Generated by Django 3.0.7 on 2021-04-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_applycandidates_is_invited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applycandidates',
            name='candidate',
        ),
    ]
