# Generated by Django 3.1.5 on 2021-04-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20210419_1445'),
        ('jobs', '0005_remove_applycandidates_candidate'),
    ]

    operations = [
    ]
