# Generated by Django 3.0.7 on 2021-04-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_applycandidates_candidate'),
        ('jobs', '0005_auto_20210419_1445'),
    ]

    operations = [
    ]
