# Generated by Django 3.0.7 on 2021-04-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_merge_20210419_1319'),
        ('jobs', '0006_merge_20210419_1633'),
    ]

    operations = [
    ]
