# Generated by Django 3.0.7 on 2021-04-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_merge_20210419_1624'),
        ('jobs', '0007_merge_20210421_1529'),
    ]

    operations = [
    ]
