# Generated by Django 3.0.7 on 2021-04-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20210423_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company_logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
