# Generated by Django 3.0.7 on 2021-05-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobs_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycandidates',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
