# Generated by Django 3.0.7 on 2021-05-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_applycandidates_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applycandidates',
            name='is_invited',
            field=models.IntegerField(default=0),
        ),
    ]
