# Generated by Django 3.0.7 on 2021-05-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20210521_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='lin_req',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='loc_req',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='pho_req',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
