# Generated by Django 3.0.7 on 2021-05-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20210524_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycandidates',
            name='linkedinurl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
