# Generated by Django 3.0.7 on 2021-05-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_applycandidates_linkedinurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycandidates',
            name='apply_source',
            field=models.CharField(default='HireBeat', max_length=100),
        ),
    ]
