# Generated by Django 3.0.7 on 2021-06-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_applycandidates_apply_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applycandidates',
            name='resume_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
