# Generated by Django 3.0.7 on 2021-06-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20210607_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='eeo_req',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
