# Generated by Django 3.0.7 on 2021-07-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_jobs_eeo_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_post',
            field=models.IntegerField(default=1),
        ),
    ]
