# Generated by Django 3.0.7 on 2021-07-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20210706_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycandidates',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applycandidates',
            name='race',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
