# Generated by Django 3.0.7 on 2021-07-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20210709_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='eeo_ques_req',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
