# Generated by Django 3.0.7 on 2021-07-12 19:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_jobs_eeo_ques_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=0, max_length=50), blank=True, null=True, size=None),
        ),
    ]
