# Generated by Django 3.0.7 on 2021-07-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_auto_20210723_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applycandidates',
            name='result_rate',
            field=models.CharField(default='-1', max_length=50),
        ),
    ]
