# Generated by Django 3.0.7 on 2021-09-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_auto_20210726_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycandidates',
            name='current_stage',
            field=models.CharField(default='', max_length=100),
        ),
    ]
