# Generated by Django 3.0.7 on 2021-09-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_applycandidates_current_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applycandidates',
            name='current_stage',
            field=models.CharField(default='Resume Review', max_length=100),
        ),
    ]
