# Generated by Django 3.0.7 on 2021-09-29 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_applycandidates_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=300)),
                ('answer_type', models.CharField(default='boolean', max_length=100)),
                ('answer', models.CharField(default='yes', max_length=100)),
                ('is_must', models.BooleanField(default=False)),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Jobs')),
            ],
        ),
    ]
