# Generated by Django 3.0.7 on 2021-10-01 15:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_jobquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycandidates',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='applycandidates',
            name='questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=500), blank=True, null=True, size=None),
        ),
    ]
