# Generated by Django 3.0.7 on 2021-10-01 16:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_auto_20211001_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycandidates',
            name='qualifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=True), blank=True, null=True, size=None),
        ),
    ]
