# Generated by Django 3.0.7 on 2021-10-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_applycandidates_must_haves'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='gh_applications_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='gh_current_stage_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
