# Generated by Django 3.0.7 on 2021-10-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_auto_20211013_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='gh_applications_id',
        ),
    ]
