# Generated by Django 3.0.7 on 2021-10-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_remove_jobs_gh_applications_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='gh_job_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
