# Generated by Django 3.0.7 on 2021-10-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_jobs_gh_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='is_closed',
            field=models.IntegerField(default=0),
        ),
    ]
