# Generated by Django 3.0.7 on 2022-01-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_auto_20211025_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='first_close_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='first_publish_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
