# Generated by Django 3.0.7 on 2022-01-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_auto_20220126_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='first_close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='first_publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
