# Generated by Django 3.0.7 on 2022-02-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_premiumjoblist'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumjoblist',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
