# Generated by Django 3.0.7 on 2022-03-02 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0041_premiumjoblist_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedemail',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receivedemail',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receivedemail',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
