# Generated by Django 3.0.7 on 2022-04-07 20:15

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0042_auto_20220302_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_exp', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), blank=True, null=True, size=None)),
                ('sen_level', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), blank=True, null=True, size=None)),
                ('req_skill_set', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), blank=True, null=True, size=None)),
                ('pre_skill_set', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), blank=True, null=True, size=None)),
                ('industry_set', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), blank=True, null=True, size=None)),
                ('education_level', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), blank=True, null=True, size=None)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SourcingCandidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=100, null=True)),
                ('current_title', models.CharField(blank=True, max_length=100, null=True)),
                ('current_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('current_location', models.CharField(blank=True, max_length=100, null=True)),
                ('current_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('current_company_size', models.CharField(blank=True, max_length=100, null=True)),
                ('skillsets', models.CharField(blank=True, max_length=300, null=True)),
                ('prev_title1', models.CharField(blank=True, max_length=100, null=True)),
                ('prev_company_name1', models.CharField(blank=True, max_length=100, null=True)),
                ('prev_company_industry1', models.CharField(blank=True, max_length=100, null=True)),
                ('prev_company_size1', models.CharField(blank=True, max_length=100, null=True)),
                ('prev_title2', models.CharField(blank=True, max_length=100, null=True)),
                ('prev_company_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('prev_company_industry2', models.CharField(blank=True, max_length=100, null=True)),
                ('prev_company_size2', models.CharField(blank=True, max_length=100, null=True)),
                ('approval', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Jobs')),
                ('sourcingRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.SourcingRequest')),
            ],
        ),
    ]
