# Generated by Django 3.0.7 on 2022-04-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0043_sourcingcandidates_sourcingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcingrequest',
            name='additionalComment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sourcingrequest',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
