# Generated by Django 3.0.7 on 2022-04-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0044_auto_20220407_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcingcandidates',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcingcandidates',
            name='approval',
            field=models.IntegerField(default=1),
        ),
    ]
