# Generated by Django 3.0.7 on 2022-05-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0045_auto_20220414_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcingcandidates',
            name='skillsets',
            field=models.TextField(blank=True, null=True),
        ),
    ]
