# Generated by Django 3.0.7 on 2022-05-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0046_auto_20220510_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='jobt_job_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
