# Generated by Django 3.0.7 on 2022-05-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0047_jobs_jobt_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycandidates',
            name='apply_referer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
