# Generated by Django 3.0.7 on 2022-06-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0048_applycandidates_apply_referer'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycandidates',
            name='jt_jtochash',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='applycandidates',
            name='jt_jtocprof',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
