# Generated by Django 3.0.7 on 2022-07-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0049_auto_20220608_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applycandidates',
            name='jt_jtochash',
        ),
        migrations.RemoveField(
            model_name='applycandidates',
            name='jt_jtocprof',
        ),
        migrations.AddField(
            model_name='applycandidates',
            name='applicant_guid',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
