# Generated by Django 3.0.7 on 2022-08-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0050_auto_20220713_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
