# Generated by Django 3.0.7 on 2022-11-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0051_auto_20220825_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='page_views',
            field=models.IntegerField(default=0),
        ),
    ]
